#!/bin/bash
# BeaconMCP - quick install on a Linux host (tested on Debian/Ubuntu)
# Usage: bash deploy/install.sh

set -e

INSTALL_DIR="/opt/beaconmcp"
REPO="https://github.com/Showdown76py/BeaconMCP.git"
VENV_DIR="$INSTALL_DIR/.venv"

echo "=== BeaconMCP - Installation ==="

# 1. System dependencies
echo "[*] Checking system dependencies..."
apt-get update -qq
apt-get install -y python3 python3-pip python3-venv git

# Versioned venv package (e.g. python3.11-venv on Debian 12)
PY_VER=$(python3 -c 'import sys; print(f"python{sys.version_info.major}.{sys.version_info.minor}")')
apt-get install -y "${PY_VER}-venv" 2>/dev/null || true

# 2. Clone or update
if [ -d "$INSTALL_DIR/.git" ]; then
    echo "[*] Updating BeaconMCP..."
    cd "$INSTALL_DIR" && git pull
else
    echo "[*] Cloning BeaconMCP..."
    git clone "$REPO" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi

# 3. Python virtual environment
if [ ! -x "$VENV_DIR/bin/pip" ]; then
    echo "[*] (Re)creating the Python virtualenv..."
    rm -rf "$VENV_DIR"
    python3 -m venv "$VENV_DIR"
fi

# 4. Install Python dependencies
echo "[*] Installing Python dependencies..."
"$VENV_DIR/bin/pip" install --upgrade pip --quiet
"$VENV_DIR/bin/pip" install -e . --quiet

# 5. .env file
if [ ! -f "$INSTALL_DIR/.env" ]; then
    echo "[*] Creating .env..."
    cp .env.example .env
    echo "  .env created. Fill it with your Proxmox credentials and BMC secrets."
else
    echo "[*] Existing .env preserved."
fi

# 5.b beaconmcp.yaml config file
if [ ! -f "$INSTALL_DIR/beaconmcp.yaml" ]; then
    echo "[*] Creating beaconmcp.yaml..."
    cp beaconmcp.yaml.example beaconmcp.yaml
    echo "  beaconmcp.yaml created. Edit it to describe your topology."
else
    echo "[*] Existing beaconmcp.yaml preserved."
fi

# 5.c BEACONMCP_SESSION_KEY for the dashboard (encrypts client_secret at rest)
if ! grep -q "^BEACONMCP_SESSION_KEY=" "$INSTALL_DIR/.env"; then
    SESSION_KEY=$(openssl rand -base64 32)
    echo "" >> "$INSTALL_DIR/.env"
    echo "# Auto-generated by install.sh -- DO NOT regenerate or all dashboard sessions invalidate." >> "$INSTALL_DIR/.env"
    echo "BEACONMCP_SESSION_KEY=$SESSION_KEY" >> "$INSTALL_DIR/.env"
    echo "[*] BEACONMCP_SESSION_KEY generated in .env."
fi

if ! grep -q "^GEMINI_API_KEY=" "$INSTALL_DIR/.env"; then
    echo "[!] GEMINI_API_KEY missing from .env -- the dashboard chat will be disabled."
    echo "    Add GEMINI_API_KEY=... to /opt/beaconmcp/.env to enable it."
fi

# 6. beaconmcp wrapper in /usr/local/bin
echo "[*] Installing the 'beaconmcp' wrapper into /usr/local/bin..."
cat > /usr/local/bin/beaconmcp <<EOF
#!/bin/bash
exec $VENV_DIR/bin/python -m beaconmcp "\$@"
EOF
chmod +x /usr/local/bin/beaconmcp

# 7. systemd service
echo "[*] Installing systemd service..."
cp deploy/beaconmcp.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable beaconmcp

echo ""
echo "=== Installation complete ==="
echo ""
echo "Next steps:"
echo "  1. Edit /opt/beaconmcp/beaconmcp.yaml to describe your infrastructure."
echo "  2. Edit /opt/beaconmcp/.env with the secrets it references."
echo "  3. Validate the config: beaconmcp validate-config"
echo "  4. Create a client:      beaconmcp auth create --name 'Assistant Web'"
echo "  5. Start the service:    systemctl start beaconmcp"
echo "  6. Confirm it is up:     curl http://localhost:8420/health"
echo "  7. Put it behind a reverse proxy (HTTPS) pointing at localhost:8420."
echo ""
